apiVersion: v1
kind: Pod
metadata:
  name: hadoop-worker-1
  namespace: hadoop
spec:
  containers:
    - name: hadoop-worker
      image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
      env:
        - name: CLUSTER_NAME
          value: "hadoop-cluster"
        - name: NAMENODE
          value: "hadoop-master"
      volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop/dfs/data
  volumes:
    - name: hadoop-data
      emptyDir: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: hadoop-worker-2
  namespace: hadoop
spec:
  containers:
    - name: hadoop-worker
      image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
      env:
        - name: CLUSTER_NAME
          value: "hadoop-cluster"
        - name: NAMENODE
          value: "hadoop-master"
      volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop/dfs/data
  volumes:
    - name: hadoop-data
      emptyDir: {}
