apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-master
  namespace: hadoop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-master
  template:
    metadata:
      labels:
        app: hadoop-master
    spec:
      containers:
      - name: hadoop-master
        image: bde2020/hadoop-namenode:3.2.1-hadoop3.2.1-java8
        ports:
        - containerPort: 9870 
        - containerPort: 9000 
        env:
        - name: CLUSTER_NAME
          value: hadoop-cluster
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://hadoop-master:9000
        - name: HDFS_CONF_dfs_namenode_name_dir
          value: /hadoop/dfs/name
        volumeMounts:
        - name: hadoop-data
          mountPath: /hadoop/dfs/name
      volumes:
      - name: hadoop-data
        emptyDir: {}
